# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8

pipelines:
  default:
    - step:
        name: Install and Test
        caches:
          - nodeserver
          - nodeclient
        script: # Modify the commands below to build your repository.
          - yarn install --ignore-scripts
          - cd client && yarn install && cd ..
          - npm run migrate
          - npm test
        services: 
          - postgres
    - step:
        name: Deploy
        trigger: manual
        script:
          - git push $DOKKU_URL $BITBUCKET_COMMIT:master

definitions: 
  caches:
    nodeclient: client/node_modules
    nodeserver: node_modules
  services: 
    postgres: 
      image: postgres
