# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8

pipelines:
  default:
    - step:
        name: Install and Test
        caches:
          - nodeserver
          - nodeclient
        script:
          - make test
        services: 
          - postgres
    - step:
        name: Build image
        services:
          - docker
        script:
          - make login
          - make build push
        caches:
          - docker
    - step:
        name: Deploy Staging
        deployment: staging
        trigger: manual
        services:
          - docker
        script:
          - make login
          - make push-as-staging
          - make deploy-staging
        caches:
          - docker
  branches:
    master:
      - step:
        # assumes image is already made. will only happen when merge strategy was ff
          name: Deploy Production
          deployment: production
          script:
            - make login
            - make deploy  

definitions: 
  caches:
    nodeclient: client/node_modules
    nodeserver: node_modules
  services: 
    postgres: 
      image: postgres
    docker:
      memory: 2048
    
