REVISION_LOWERCASE := $(shell echo $(REVISION) | tr A-Z a-z)

deploy-testing:
	mkdir -p ${REVISION}
	cd ${REVISION}; \
	export REVISION_LOWERCASE=${REVISION_LOWERCASE} && envsubst < ../docker-compose.testing.yml.template > docker-compose.yml; \
	docker-compose up -d; \
	docker image prune -af;

cleanup-testing:
	if [ -d "${REVISION}" ]; then \
		cd ${REVISION}; \
		docker-compose down; \
		cd ..; \
		rm -rf ${REVISION}; \
	fi
	docker image prune -af